light:
- platform: mqtt 
  schema: json
  name: "PinkyLED1"
  command_topic: "cmnd/PinkyLED1"
  state_topic: "stat/PinkyLED1"
  availability_topic: "LWT/PinkyLED1"
  payload_available:  "Online"
  payload_not_available: "Offline"
  white_value: true
  optimistic: false
  rgb: true
  flash_time_short: 1
  flash_time_long: 5
  brightness: true
  effect: true
  effect_list:
    - "Confetti Color"
    - "Glitter Color"
    - "Juggle Color"
    - "Sinelon Color"
    - "Solid Color"
    - "Christmas"
    - "Candy Cane"
    - "Holly Jolly"
    - "Valentine"
    - "Lovey Day"
    - "St Patty"
    - "Easter"
    - "USA"
    - "Independence"
    - "Go Blue"
    - "Hail"
    - "Touchdown"
    - "Halloween"
    - "Punkin"
    - "Thanksgiving"
    - "Turkey Day"
    - "BPM"
    - "Cyclon Rainbow"
    - "Dots"
    - "Fire"
    - "Lightning"
    - "Police All"
    - "Police One"
    - "Rainbow"
    - "Glitter Rainbow"
    - "Ripple"
    - "Twinkle"
    - "Audio Color"
    - "Audio Level Rainbow"
    - "E131"
